### ISSUE TITLE
Getting Detected on Amazon Ec2

### ISSUE THREAD

**Issue by jckail** [ultrafunkamsterdam/undetected-chromedriver#10]
First off SUPER cool project. Works flawlessly local on mac. 

Getting Detected on Amazon Ec2 Instance. My instinct is telling me I'm getting detected by some Amazon/ Ec2 Detection from the site. 

Let me know what details I can provide and how I can contribute to the project! :) ps - I'll be uploading the repo I'm working on that uses yours some time today, just have to package.

**Comment by ultrafunkamsterdam** [comment]
Couple of gotcha's:

You need to browse only programmatically .  Always use driver.get('https://yoururl'), 
*never-ever* browse manually by just using the browser window and your keyboard,  because then the anti-detection logic will not do it's thing before the page load, And once detected, your browser fingerprint + ip will definitely trigger another one,2 or 10 until you solved a couple.
Please provide the url you are targeting so i can test it.

**Comment by ultrafunkamsterdam** [comment]
Closing due to no response

**Comment by jckail** [comment]
Created task https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/11
