### ISSUE TITLE
V2 Options Issue

### ISSUE THREAD

**Issue by fravegl** [ultrafunkamsterdam/undetected-chromedriver#109]
Using the following code I can't set the desired settings using V2 chromedriver.

import undetected_chromedriver.v2 as uc
options = uc.ChromeOptions()
options.add_argument("user-data-dir=selenium")
driver = uc.Chrome(options=options)
with driver:
    driver.get('https://addmefast.com')

**Comment by ultrafunkamsterdam** [comment]
@fravegl 

Make sure the folder does not exist yet, but better: just don't define it. the module takes care of the datadir using tempfolders which are removed afterwards. You cannot specify an existing folder which is already used.

**Comment by sagistrauss** [comment]
Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.

**Comment by ultrafunkamsterdam** [comment]
> Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.
> I edited v2.py to not delete the user data dir, I'm getting the restore popup issue which is easily fixable, but script fails with cloudflare. What's left in that folder that 

> Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.
> I edited v2.py to not delete the user data dir, I'm getting the restore popup issue which is easily fixable, but script fails with cloudflare. What's left in that folder that triggers their engine?

Well. That is my question as well. I guess something is linked between the driver and profile,  probably the $cdc variables but these are  randomly created by the module, thus they do not match the profile, IF that plays a role anyway.
Could you post the fix  for that popup thing you mentioned?  Would save me some invaluable time. Thanks

**Comment by aleixrodri98** [comment]
Hey mate, try adding this argument: "--disable-features=InfiniteSessionRestore"

**Comment by fravegl** [comment]
> Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.
> I edited v2.py to not delete the user data dir, I'm getting the restore popup issue which is easily fixable, but script fails with cloudflare. What's left in that folder that triggers their engine?

I managed to fix the problem myself using the following code insted of the one in my firstpost.

import undetected_chromedriver.v2 as uc
driver = uc.Chrome(user_data_dir="seleenium")
driver.get_in('https://google.com')

**Comment by ultrafunkamsterdam** [comment]
> > Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.
> > I edited v2.py to not delete the user data dir, I'm getting the restore popup issue which is easily fixable, but script fails with cloudflare. What's left in that folder that triggers their engine?
> 
> I managed to fix the problem myself using the following code insted of the one in my firstpost.
> 
> import undetected_chromedriver.v2 as uc
> driver = uc.Chrome(user_data_dir="YOUR_DIRECTORY")
> driver.get_in('https://google.com')
Thanks for your input! Oh well even better, a documented flat.   But......... the clouflare things as mentioned some replies above, bypassing also works using this solutions, and also picks  up the folder correctly when the driver binary changes (easy test by deleting chromedriver and rerun the snippet)? 

Since this module is aiming primarily on (un)discoverability, i will happily add this extra functionality, But should not break the core purpose :)

**Comment by sagistrauss** [comment]
> > Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.
> > I edited v2.py to not delete the user data dir, I'm getting the restore popup issue which is easily fixable, but script fails with cloudflare. What's left in that folder that
> 
> > Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.
> > I edited v2.py to not delete the user data dir, I'm getting the restore popup issue which is easily fixable, but script fails with cloudflare. What's left in that folder that triggers their engine?
> 
> Well. That is my question as well. I guess something is linked between the driver and profile, probably the $cdc variables but these are randomly created by the module, thus they do not match the profile, IF that plays a role anyway.
> Could you post the fix for that popup thing you mentioned? Would save me some invaluable time. Thanks

Hey there, so I decided not to use the same user-data-dir, instead I keep sessions using pickle and reload them whenever I need. I chose that solution to try and stay bulletproof, as you said that you think there are footprints that can get detected, I haven't checked that claim myself and would love to have a chat about it. 

To remove the first run popup that happens when you use a new data-dir, I created a file named First Run when you create the temp folder on v2. 

`        if not user_data_dir:
            user_data_dir = os.path.normpath(tempfile.mkdtemp())
            os.mknod(user_data_dir+"/First Run")`

To get rid of the 'restore session' issue I had when trying to use the same data-dir I changed the Preferences file:

`filedata = filedata.replace('"exit_type":"Crashed"','"exit_type":"none"')
`

But that's a nasty hack, I need to look more at your driver quit function, because at the first place the exit type shouldn't be crashed. Also, I'm noticing that when I don't set a user-dir, the user dir is being created by your code, but there are two issues: 
- For some reason, Chrome creates additional dirs in /tmp named .com.google.Chrome.* but that might be because I'm loading cookies and for some reason they are kept there.
- There's a file not found exception when I try to do driver.quit() as your code tries to delete the folder that was created, but it's already deleted (I assume chromedriver takes care of that, didn't check)
`        # try:
        #     shutil.rmtree(self.user_data_dir, ignore_errors=False)
        # except (PermissionError, FileNotFoundError):
        #     time.sleep(1)
        #     self.quit()`

Anyhow, great work, I'd love to chat about the project and be an active contributor.

**Comment by ultrafunkamsterdam** [comment]
I will further read in later, but this looks pretty much like you are using macos ? That has this terrible unstoppable first run screen. On Mar 2, 2021 09:20, Sagi Strauss <notifications@github.com> wrote:


Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.
I edited v2.py to not delete the user data dir, I'm getting the restore popup issue which is easily fixable, but script fails with cloudflare. What's left in that folder that


Hrm, why wouldn't the module allow the use of existing folder? I'd like to use previous sessions etc.
I edited v2.py to not delete the user data dir, I'm getting the restore popup issue which is easily fixable, but script fails with cloudflare. What's left in that folder that triggers their engine?

Well. That is my question as well. I guess something is linked between the driver and profile, probably the $cdc variables but these are randomly created by the module, thus they do not match the profile, IF that plays a role anyway.
Could you post the fix for that popup thing you mentioned? Would save me some invaluable time. Thanks

Hey there, so I decided not to use the same user-data-dir, instead I keep sessions using pickle and reload them whenever I need. I chose that solution to try and stay bulletproof, as you said that you think there are footprints that can get detected, I haven't checked that claim myself and would love to have a chat about it.
To remove the first run popup that happens when you use a new data-dir, I created a file named First Run when you create the temp folder on v2.
        if not user_data_dir: user_data_dir = os.path.normpath(tempfile.mkdtemp()) os.mknod(user_data_dir+"/First Run")
To get rid of the 'restore session' issue I had when trying to use the same data-dir I changed the Preferences file:
filedata = filedata.replace('"exit_type":"Crashed"','"exit_type":"none"') 
But that's a nasty hack, I need to look more at your driver quit function, because at the first place the exit type shouldn't be crashed. Also, I'm noticing that when I don't set a user-dir, the user dir is being created by your code, but there are two issues:
For some reason, Chrome creates additional dirs in /tmp named .com.google.Chrome.* but that might be because I'm loading cookies and for some reason they are kept there.There's a file not found exception when I try to do driver.quit() as your code tries to delete the folder that was created, but it's already deleted (I assume chromedriver takes care of that, didn't check)
        # try: #     shutil.rmtree(self.user_data_dir, ignore_errors=False) # except (PermissionError, FileNotFoundError): #     time.sleep(1) #     self.quit()
Anyhow, great work, I'd love to chat about the project and be an active contributor.
