### ISSUE TITLE
Cloudflare Proxy

### ISSUE THREAD

**Issue by STRATZ-Ken** [ultrafunkamsterdam/undetected-chromedriver#112]
Hello,

Is there anyway to get past Cloudflare with a proxy with this?  The exe works perfectly without `--proxy-server=127.0.0.1:8000`. However once I add it, Cloudflare stops.  Is there anyway to capture the data outbound and apply a proxy through another means?

**Comment by ultrafunkamsterdam** [comment]
yes, use v2, and no proxy at all..

**Comment by vesper8** [comment]
@ultrafunkamsterdam The whole reason I use proxies is so I don't get my production server's ip blacklisted. But you're suggesting not to use a proxy.. what am I missing? If I get caught even once my IP may be blacklisted forever.

**Comment by Avnsx** [comment]
@vesper8 if you're using proxies and your project is profitable, re-invest into it by using high quality proxies. For example the residental ones, from luminati.io are really good. That'll help you the most if you really wanna use proxies and still bypass CF

**Comment by vesper8** [comment]
@Avnsx Thanks, that's good advice for sure. But my project is brand new and not yet profitable. I will keep luminati.io in mind for the future. In any case however, it seems like v2 is not yet compatible with proxies? Or no one's figured out how to make it work with proxies.

How do you currently get around CF's protection using proxies?

Luckily I can get around CF's protection by doing the scraping from my local machine, and then uploading the results to my server. I guess that's because my local IP has been flagged as clean since I also use it to visit the site I'm scraping.

**Comment by ultrafunkamsterdam** [comment]
> @ultrafunkamsterdam The whole reason I use proxies is so I don't get my production server's ip blacklisted. But you're suggesting not to use a proxy.. what am I missing? If I get caught even once my IP may be blacklisted forever.

Haha:) not forever, silly. 

Abother tip, use nordvpn. Not expensive and they offer proxies as well, although programming against their api iets you switch between vpn's as well. Regering proxy use in v2 check my response here for example https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/117#issuecomment-806277603
