### ISSUE TITLE
Using different versions of Chrome

### ISSUE THREAD

**Issue by arigatou** [ultrafunkamsterdam/undetected-chromedriver#114]
Hello,

I am using undetected-driver v2 and it is doing a fantastic job of bypassing CF & Datadome.

Is there any way to implement this driver and use various versions of Chrome (Chrome 89, Chrome 88, Chrome 87) in one script?

What would it look like code-wise? I am currently using multi-process to launch up to 16 threads of Chrome and operating simultaneously, but I fear I have one major pattern which is all my actions have a consistent useragent, and I need that changed but it won't be enough to set the useragent and spoof it, I believe that was detected every time I tried, so I've got to launch actual different versions of Chrome and not spoof anything.

Also, for some reason I cannot get the options to work for v2, only v1, is there a different way to put options while using v2? For now I've resorted to just editing v2.py to add my options to the default since I need them the same everytime, but I do have use cases where I want to specify different launch arguments per process.

**Comment by ultrafunkamsterdam** [comment]
Yes, it would be possible, but i'm not going to write it all out for you i'm sorry. Comes down to:
 You should be having the 3 chrome versions installed first. Then you should use Patcher class to download and patch the binaries for each version (and rename the patched binaries in between otherwise they overwrite each other). And then you should get 3 configs, specifying the 3 different executables of chrome binary AND making sure the each config also uses the correct chromedriver binary.

**Comment by ultrafunkamsterdam** [comment]
regarding the options. it depends. I recommend not to use any other than the ones used already.. the rest of the options won't work in remote-debugging-mode ,which v2 uses. 

```
options = uc.ChromeOptions()
options.debugger_address = debug_addr
options.binary_location = find_chrome_executable()
```
of course there are "some" that will work (like headless=True), but that is still detectable so i don't advertise using it.
