### ISSUE TITLE
Cloudflare challenge issue

### ISSUE THREAD

**Issue by valodzka** [ultrafunkamsterdam/undetected-chromedriver#149]
Code below doesn't work (but opening in browser directly does):

```
import undetected_chromedriver as uc

driver = uc.Chrome()

driver.get('https://hidemy.name/en/proxy-list/')
```

**Comment by amitalokbera** [comment]
use v2, it will bypass the Cloudflare protection

import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
with driver:
    driver.get('https://hidemy.name/en/proxy-list/')

**Comment by kaislaribi** [comment]
i am trying to scrap one page of zoominfo using this, but still get the cloudflare page with captcha. Also Chrome gives a pop up window  asking to set it as default navigator. Any idea why ? 

```
  import undetected_chromedriver.v2 as uc
  proxy = get_proxy()
  chrome_options = webdriver.ChromeOptions()
  chrome_options.add_argument('--proxy-server=%s' % proxy)  # , chrome_options=chrome_options
  driver = uc.Chrome(options=chrome_options)

  with driver:
      driver.get('https://www.zoominfo.com/c/epa-digital/542474933')

```

**Comment by amitalokbera** [comment]
don't use Proxy server, using the proxy server breaks the internal function of the v2

**Comment by kaislaribi** [comment]
But in this case there is a risk the ip of the server get banned? 
What about the popup window to set chrome as default browser, do you have any idea?

**Comment by valodzka** [comment]
> use v2, it will bypass the Cloudflare protection

Thank you, it works. I just used _recommended_ way. Maybe it's worth updating documentation about v2 usage.

**Comment by ultrafunkamsterdam** [comment]
> But in this case there is a risk the ip of the server get banned?
> What about the popup window to set chrome as default browser, do you have any idea?

You must do real bad things for an ip address to be banned. For websites, the worst that happens (USUALLY) is your ip being flagged by cloudflare. Since half internet is behind cloudflare, this also goes for other website which you may not even scrape. after some normal usage and 1 or 2 captcha solving the flag is removed. I'm busy finding a loophole to "save" the chrome profile (in a way you can reuse it). At the moment, a profile will be created and deleted for each run.
