### ISSUE TITLE
[question] Patching binary

### ISSUE THREAD

**Issue by aleixrodri98** [ultrafunkamsterdam/undetected-chromedriver#20]
Hello mate,

I would like to thank your amazing work, I do understand everything you do and its absolutely brilliant. I already investigated this a while ago but used a really worse solution than you that was using a MITM proxy and injecting javascript on each request to remove webdriver property etc.

I have one question though, why do you patch the binary and what do you exactly do with that? I see you modify the binary but don't understand how.

Thanks a lot,
Aleix

**Comment by azamet90** [comment]
maybe since him is not answering is the answer :D

**Comment by TJM4** [comment]
There is a variable called cdc which is the same for all Chrome driver binaries. You need to patch the binary to change this value so that sites can't detect it. See https://stackoverflow.com/a/52108199/5863898

**Comment by ultrafunkamsterdam** [comment]
^^ that

**Comment by ultrafunkamsterdam** [comment]
In case you need to known the  "how" in  technical terms,  that can be seen in the code.  Method "patch_binary". It actually searches for the key,  which (which in unpatched drivers, shows up in dev console as  window variable $cdc_xyz . Replacing it to an equally length bytestring does the same, but since it's  it had another name....
