### ISSUE TITLE
wrong version chromedriver is being downloaded?

### ISSUE THREAD

**Issue by cybernetic87** [ultrafunkamsterdam/undetected-chromedriver#204]
Hello,

I'm using undetected chromedriver on Ubuntu 16.04, latest chrome  version available in ubuntu repos is 90, I download suitable chromedriver through dockerfile and it works fine without the UC. However after I install / import UC I am getting an error that the chromedriver only supports chrome 91. Shouldnt it automatically detect the chromium-browser version I have on my system instead of having me explicitly specify target_version? 

Btw. providing an executable_path to chromedriver_binary doesnt work as well, only specifying target version works.

UC 3.0.1
MonkeyPatch mode uc.install()

Thanks,

**Comment by koljaoh** [comment]
How do you specify the target version? uc.TARGET_VERSION = 91 doesn't work

I have the same/a similar issue. I'm still using v1 (due to problems with headless in v2) and I have the latest chromedriver (in path and recognized) but when I try to run uc it says "This version of ChromeDriver only supports Chrome version 89". 

and by the way, setting executable path also doesnt work
uc.install(
    executable_path=r"C:\bin\chromedriver.exe"
)

**Comment by daltonxiong** [comment]
i do this on ubuntu
`
version_str = os.popen('google-chrome --version')
output = version_str.read()
v1, v2, v3, v4 = re.search(r'Google Chrome (\d+)\.(\d+)\.(\d+)\.(\d+)', output).groups()
driver = uc.Chrome(version_main=int(v1))
`

**Comment by ultrafunkamsterdam** [comment]
```python
driver = uc.Chrome(version_main=90)
```
Life can be so easy.
