### ISSUE TITLE
typeError: __init__() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by liqing1990** [ultrafunkamsterdam/undetected-chromedriver#22]
The following is my environment and code
MacOS Mojave 10.14.4
chrome:84

> import undetected_chromedriver as uc
chromedriver_path='./chromedriver'
uc.install(executable_path=chromedriver_path)
from selenium.webdriver import Chrome,ChromeOptions
option = ChromeOptions()
option.add_argument('--disable-popup-blocking')
driver = Chrome(chrome_options=option)
driver.get('https://distilnetworks.com')

The following is the error message

> Selenium patched. Safe to import Chrome / ChromeOptions
Selenium patched. Safe to import Chrome / ChromeOptions
Selenium patched. Safe to import Chrome / ChromeOptions
Selenium patched. Safe to import Chrome / ChromeOptions
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/mac_lee/Documents/iCollections/work/python/workspace/bet365_spider/test0810.py", line 11, in <module>
    driver = Chrome(chrome_options=option)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/__init__.py", line 49, in __new__
    instance.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'options'

Can you know why this is?

**Comment by ultrafunkamsterdam** [comment]
Hi there @liqing1990 , 

I'm not sure about this, but i cannot find a single thing that is correct, even the exception ```File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/undetected_chromedriver/init.py", line 49, in new
instance.init(*args, **kwargs)
TypeError: init() got an unexpected keyword argument 'options'``` does not point to a file even included in this library (it consists of only __init__.py .  Either you made modifications yourself or whatnot. Recommendation: Please install the latest version of python and this package, and please first try importing and using it as described in the README.md.  Also, you don't need to import Chrome and ChromeOptions from selenium (well you can and it should work, but i don't see any reason for it in your use case). You can use uc.ChromeOptions and uc.Chrome as well. Also specifying the executable path is not needed, since these options are included by default. Furthermore. Chrome accepts an `options` parameter but not `chrome_options`.  

(i tested it on Mojave as well and it worked out of the box)

Kind regards

**Comment by chryahya** [comment]
Hi, i have the same error
My environement : windows server 2012, Chrome Last version, python 3.7 & python 3.8

My Code :
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://distilnetworks.com')

The Error :
/python3.8/site-packages/undetected_chromedriver/init.py", line 49, in new instance.init(*args, **kwargs) TypeError: init() got an unexpected keyword argument 'options'

This is the screenshot :
https://i.ibb.co/PMPts9L/Error-bot.png

NOTE :
i have two windows server 2012 with the same configuration and same chrome & python & same code
one of them work well, and the other i have the error.

Thank you
