### ISSUE TITLE
Can't Use detach True mode

### ISSUE THREAD

**Issue by oyi77** [ultrafunkamsterdam/undetected-chromedriver#241]
Hi, i am a newbie here. I have try it many times but it seems that it always hang whenever i add the options.add_experimental_option("detach", True)

Do you wonder why?

**Comment by wtfismyname69420** [comment]
I am also experiencing this issue. A resolution would be appreciated

**Comment by ultrafunkamsterdam** [comment]
probably because this works a little different than the regular driver. 

The regular driver opens the chrome browser for you and is able to apply this option.

In this version, the browser is opened by python. So in fact you are already "detached" and can close a driver and keep the browser window open (for whatever reason you may want that). 

to kill the driver and not the window use  driver.service.stop()

**Comment by oyi77** [comment]
thankyou i will try that thanks dude
