### ISSUE TITLE
Frequent chromedriver errors when running multi-threaded?

### ISSUE THREAD

**Issue by thanhvodad** [ultrafunkamsterdam/undetected-chromedriver#242]
When running multi-threading I often get the error Google Chrome STOP, choromedrier.exe Application Error. Is there a guide to fix this error :(

**Comment by ultrafunkamsterdam** [comment]
Run single threaded. Makes  no sense doing mt as the chromedriver and browser  are separate processes. And have only small io overhead .

**Comment by HMaker** [comment]
You can run multithread, but only 1 thread can interact with the driver. So if you need 10 threads, create 10 drivers, one for each and don't share drivers between threads.

**Comment by iamat8080** [comment]
@HMaker how would i fo that

**Comment by HMaker** [comment]
@iamat8080 like this
```python
import time
import threading
from undetected_chromedriver.v2 import Chrome


def start_driver_thread():
    driver = Chrome()
    time.sleep(10)

threads = []
for _ in range(3):
    t = threading.Thread(target=start_driver_thread)
    t.daemon = True
    t.start()
    threads.append(t)

for t in threads:
    t.join()
```

**Comment by Nux-xader** [comment]
> @iamat8080 like this
> 
> ```python
> import time
> import threading
> from undetected_chromedriver.v2 import Chrome
> 
> 
> def start_driver_thread():
>     driver = Chrome()
>     time.sleep(10)
> 
> threads = []
> for _ in range(3):
>     t = threading.Thread(target=start_driver_thread)
>     t.daemon = True
>     t.start()
>     threads.append(t)
> 
> for t in threads:
>     t.join()
> ```
join need 1 arg bro

**Comment by Nux-xader** [comment]
> @iamat8080 like this
> 
> ```python
> import time
> import threading
> from undetected_chromedriver.v2 import Chrome
> 
> 
> def start_driver_thread():
>     driver = Chrome()
>     time.sleep(10)
> 
> threads = []
> for _ in range(3):
>     t = threading.Thread(target=start_driver_thread)
>     t.daemon = True
>     t.start()
>     threads.append(t)
> 
> for t in threads:
>     t.join()
> ```

its not working for me 
i get same error
    self.service.process.kill()
AttributeError: 'Chrome' object has no attribute 'service'

**Comment by iamat8080** [comment]
just change the port on each thread and pass executable it'll work
![image](https://user-images.githubusercontent.com/47313918/134090674-8dc4dcf1-4d36-4281-9d82-6476334b5c34.png)

**Comment by zanjs** [comment]
@iamat8080  

```python
import time
import threading
import undetected_chromedriver as uc


def start_driver_thread(prot):
    print(prot)
    driver = uc.Chrome(browser_executable_path=r"C:\Program Files\Google\Chrome\Application\chromedriver.exe", port=prot)
    # driver = uc.Chrome(port=prot)
    time.sleep(10)

if __name__ == "__main__":
    threads = []
    for i in range(3):
        print(i)
        t = threading.Thread(target=start_driver_thread, args=(i+8000,))
        t.daemon = True
        t.start()
        threads.append(t)

    for t in threads:
        t.join()
```

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\root\\appdata\\roaming\\undetected_chromedriver\\chromedriver.exe'

**Comment by saksham-lussqvx** [comment]
I've found a solution to this, first download the version undetected_chromedriver==3.2.0 and use chrome version between 108-110 because they work flawlessly with these, also if you're still facing issue, set the version to your chrome version and download chromedriver, for chromedriver you can also use chromedriver_autoinstaller libary.  Here is a sample code for it:

import undetected_chromedriver as uc

options = uc.ChromeOptions()
options.add_argument('--log-level=2')
options.add_argument('--headless') #comment this if needed
options.add_argument("--disable-extensions")
options.add_argument('--disable-application-cache')
options.add_argument('--disable-gpu')
options.add_argument("--no-sandbox")
options.add_argument("--disable-setuid-sandbox")
options.add_argument("--disable-dev-shm-usage")
driver = uc.Chrome(options=options,version_main=109)

driver.get("www.google.com")

Hope this helps y'all!
