### ISSUE TITLE
UC is detected when using headless mode

### ISSUE THREAD

**Issue by yummyhon** [ultrafunkamsterdam/undetected-chromedriver#258]
When visiting gumtree at this link: https://www.gumtree.com.au/t-login-form.html it loads when UC is not headless.

However, when i turn on headless mode, then it does not work. It gets stuck at loading the page. I saw the same behavior when I was using selenium with just normal chrome (not UC)

This is the code I am using:

```
    import undetected_chromedriver.v2 as uc
    options = uc.ChromeOptions()
    options.headless = True

    driver = uc.Chrome(version_main=92, options=options)
    driver.get('https://www.gumtree.com.au/t-login-form.html') 
```

**Comment by viper645** [comment]
Just look online you can easily find solutions to not get detected on headless mode with selenium.

**Comment by yummyhon** [comment]
@viper645 but wasn’t the whole point of this module to prevent detection without much effort from the user?

If I have to manually circumvent detection, Why would I even use this module?

**Comment by senic35** [comment]
@yummyhon Since this repo got really popular all of a sudden with people like you trying to circumvent all possible bot + spam filters by just writing 2 lines of code, websites and spam/bot blocking networks are fighting back of course.
Given the case you really need an undetectable solution for your target website, learn more about fingerprinting and custom patching yourself or pay someone to do it.
This is a cat-and-mouse game and its only going to get tougher from here on out.

**Comment by ultrafunkamsterdam** [comment]
The answer is simple. Headless mode is not supported (well, it works for most simple detections, but not yet for CloudFlare IUAM, the heaviest and most intrusive of all). Only the headed version is able to bypass.

**Comment by HMaker** [comment]
Headless can be easily detected as shown by #273 which does not detects just UC but any patch done to browser env to make headless undetectable.
