### ISSUE TITLE
[AliExpress Bonus Buddies] Mobile Taps Being Detected!

### ISSUE THREAD

**Issue by Syntist** [ultrafunkamsterdam/undetected-chromedriver#31]
If someone can help me out.. would mean alot! 
I have spend all night trying to resolve.. so the problem is

I made a Automate Script for AliExpress Bonus Buddies, before the update it didn't required Touch! But now it require touch.. i used your chrome driver before and it couldn't be detected but now I am having issue

If Bot press tap it isn't accepted, If I press the tap it's accepted!! 

Human Touch (Mobile View)  - iPhone X:
![image](https://user-images.githubusercontent.com/24858150/94630487-5d3a5a80-02df-11eb-99d9-01f5bb273c12.png)
![image](https://user-images.githubusercontent.com/24858150/94630491-60354b00-02df-11eb-874a-70bab53353d0.png)

Bot Touch (Mobile View) - iPhone X:
![image](https://user-images.githubusercontent.com/24858150/94630905-7ee81180-02e0-11eb-880d-8bf85ef0f42f.png)
![image](https://user-images.githubusercontent.com/24858150/94630908-814a6b80-02e0-11eb-8123-968a4e96dde9.png)

Though.. undected-chromedriver fixed this issue! before when it can be just get clicked with click() but now it doesn't work

To Use Touch I had to disable W3C! maybe that can be the cause, would love a solution for this problem!

**Comment by HarryBak** [comment]
If the scratch is always the same coords I'd suggest trying pyautogui

**Comment by Syntist** [comment]
Ya, but that defeats the purpose of running it in background or in headless mode!

**Comment by ultrafunkamsterdam** [comment]
You altered more than just some settings. since the "Chrome is being controlled by automated test software"  not displayed by default. And incognito screen... i suspect you opened this manually, and would like to refer you back to the readme (read the part about manual actions) . Use default settings first, and then try the console log switch   Chrome(enable_console_log=True),  also:  You should be testing all children and sibbling elements around the "target". Very often, sites are protecting theirselves by wrapping multiple elements and make the outer one's or inner ones (depending on use case), listen to the click event. This to prevent the  bots looking for the "obvious", instagram and google are especially good at this.
