### ISSUE TITLE
Patched chrome binary goes to the current folder

### ISSUE THREAD

**Issue by cptx032** [ultrafunkamsterdam/undetected-chromedriver#350]
Hi! Thanks for this amazing library!
I'm using chrome driver manager with undetected-chromedriver as follows:

```python
    driver = Chrome(
        seleniumwire_options=seleniumwire_options,
        options=_chrome_options,
        executable_path=ChromeDriverManager().install(),  # <<<<<
    )
```

The result of `ChromeDriverManager().install()` return `~/.wdm/drivers/chromedriver/linux64/95.0.4638.69/chromedriver` which is expected, but in the current folder, a `chromedriver` binary is created.

Is this binary the patched chromedriver? How can I choose where to store this file?

**Comment by nhwalkman** [comment]
I don't know if this is a patched chromedriver, but the statement "ChromeDriverManager().install()" appears to be working.

Therefore, since it is creating a chromedriver it seems that you have a few options as a simple work around.
1. change your environment PATH variable to include this DIR
2. add some code to either copy or move the newly formed chromedriver before using your driver object.
3. simply destroy this driver object and re-instantiate it (2 statements):
initialize object
`driver = Chrome(
        seleniumwire_options=seleniumwire_options,
        options=_chrome_options,
        executable_path=ChromeDriverManager().install() )`
redefine object: reference path to the appropriate driver
`driver = Chrome(
        seleniumwire_options=seleniumwire_options,
        options=_chrome_options,
        executable_path=your_new_path )`

**Comment by cptx032** [comment]
Hi! Thanks for the reply!
> I don't know if this is a patched chromedriver

It is!
I've found that the `executable_path` argument must be passed to the chrome_options and not to `Chrome` class. But after that, the code only patch the binary if the executable doesn't exist. So in the end I've just copied the patch methods in my project and works fine now.

Thanks!
