### ISSUE TITLE
Recommendation on variable replacement

### ISSUE THREAD

**Issue by frzsombor** [ultrafunkamsterdam/undetected-chromedriver#38]
Just thinking out loud about the [latest changes](https://github.com/ultrafunkamsterdam/undetected-chromedriver/commit/4ce47e7f83ea288509a05b21b2a8806fed3da239#diff-b1415858986f3be41e64bac68e30d09ac7a9713f92af3a2177bbd193e8393bc2R233): I wouldn't use a hardcoded replacement like this, because it is also very easy to block, just like "cdc_adoQpo[...]" (if any anti-bot service follows this repo). Instead, I would generate a random string (equal in length to the original string) and use that, as a replacement. 

However I do **love** the fact and the _easter egg_, that you used "undetectedchromeDRiver" as it is exactly, perfectly the same length as the original, made up variable.

**Comment by ultrafunkamsterdam** [comment]
I think we're on the same page :) nice, to see someone actually noticing this :) It was my idea (and of course better practice) as well to make it random, but noticed this would fit perfectly. So until some major anti-bot service anticipates on it (which would be awesome, seeing this project name in their source), I'll keep it like this

**Comment by ultrafunkamsterdam** [comment]
And by major anti-bot service i'm not pointing at you @botprotect.io  

Remember I still got your source code, only to be released whenever you got your website finished and some customers. I know, that is gay__, but i think  you better doSomeRandomShit instead of opening an issue in my repo advertising your service.
