### ISSUE TITLE
Chrome Turns Off Automatically As It Connects to the Site

### ISSUE THREAD

**Issue by elventyildiran** [ultrafunkamsterdam/undetected-chromedriver#450]
Hello, as I mentioned in the title, it closes as it enters the site. I'll leave the sample code downstairs. Is this shutdown normal? How do I get ahead of this?

```
import undetected_chromedriver as uc
driver = uc.Chrome()
driver.get('https://google.com')
```

And secondly, I'm having the following problem. How do I get out of this problem?
![2022-01-12_23h33_06](https://user-images.githubusercontent.com/85314065/149217433-1dc641a7-7ee4-4d81-a44e-514629f22a41.png)

Thanks

**Comment by KrzysztofKalisiak** [comment]
Its happening mainly because your code just ends executing, error is probably connected to fact that you do not quit browser before program closes.
Try adding:
'time.sleep(10)
driver.quit()'

It will make your program wait 10 seconds before ending as there is just no tasks to execute

**Comment by elventyildiran** [comment]
when I add "time.sleep(10)", it doesn't turn off, yes. So is this the behavior that should be happening? I want to learn.

**Comment by KrzysztofKalisiak** [comment]
Basically executing python script and running children process, which is running chromedriver in that example are 2 different things.
Driver.get('something) is just telling python to get redirect driver to wanted page, its not telling him to wait till you do something on that page, because well, how should he know when to go forward with code execution? 
As soon as python gets to the end of the code it just ends program resulting in terminating all child processes (usually).

Usually you want him to do something like scrapping, if you dont want anything for him to do and you dont want to code to stop executing and the child process to kill you can close it in some infinite loop.

**Comment by elventyildiran** [comment]
Yes, now I understand, thank you very much :)  So how do I solve the problem I showed in the picture?

**Comment by KrzysztofKalisiak** [comment]
Depends on what you are trying to achieve.

**Comment by elventyildiran** [comment]
When I run it, I need to open google directly, but I get the error in this image.

**Comment by KrzysztofKalisiak** [comment]
What do you want to do after you open google?

**Comment by RealKien** [comment]
@KrzysztofKalisiak Hi, can you help me with a similar issue https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/533? My undetected chromedriver suddenly quit even before it can finished executing any Python codes....
