### ISSUE TITLE
WebDriverException 'chromedriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by axiangcoding** [ultrafunkamsterdam/undetected-chromedriver#468]
im using UC inside docker image  `python:3.10-alpine`, 
my Dockerfile:
```
FROM python:3.10-alpine
RUN apk update && apk upgrade && apk add --no-cache gcc libressl-dev musl-dev libffi-dev chromium chromium-chromedriver
ENV PATH="/usr/bin/chromedriver:${PATH}"

WORKDIR /app
COPY . /app/
RUN pip install -r requirements.txt
# exec scrapy
ENTRYPOINT ["python", "-u","main.py"]
```
but when i run my script, it shows:
```
2022-01-26 17:34:11 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/undetected_chromedriver/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 86, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/scrapy/crawler.py", line 98, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/scrapy/spiders/__init__.py", line 50, in from_crawler
    spider = cls(*args, **kwargs)
  File "/app/crawler/spiders/gaijin_cloudflare.py", line 22, in __init__
    self.driver = uc.Chrome(options=options, suppress_welcome=True)
  File "/usr/local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 369, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

```
PATH env:
```
PATH=/usr/bin/chromedriver:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
chromedriver already in PATH, located in "/usr/bin/chromedriver"
and i exec command `chromedriver` directly, it seems works fine:
```
/app # chromedriver
Starting ChromeDriver 93.0.4577.82 (e3a25d9b9e2d0b728e045ec87c0aa4942aa46e4e-refs/branch-heads/4577@{#1237}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[1643218468.692][SEVERE]: bind() failed: Address not available (99)
ChromeDriver was started successfully.

```

Where could the problem be? missing dependencies?

**Comment by spacekomet** [comment]
UC downloads new version of cromedriver each time you run it, You can see the actual downloaded path in your log, which gives you the error:
/root/.local/share/undetected_chromedriver/chromedriver
Try to run that file manually. 

In my case, on rpi4 (aarch64), uc downloaded linux x64 cromedriver, which couldn't be started due to wrong architecture.
Solution for me was, to change the uc source code, to not download (overwrite) the file every time, but rather patch already existing cromedriver (compiled for aarch64). For this I had also to bring back the parameter for driver path, similar to this https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/434 .

**Comment by rtrive** [comment]
is there a solution to this problem? I have this problem on python3.9-alpine

**Comment by ultrafunkamsterdam** [comment]
@axiangcoding

https://hub.docker.com/r/ultrafunk/undetected-chromedriver

**Comment by sanchouz12** [comment]
If anyone has this problem, I was able to pull it off without UC image. I just passed path to my chrome driver into Chrome instance using `driver_executable_path` parameter.
Used versions: UC 3.1.5.post4, Python 3.10.4r0, Docker container - Alpine 3.16.0

**Comment by disposablecarcass** [comment]
I've been troubleshooting this for some time and made a github account to share my insight. Here is what worked for me:

1. Be sure to set the version when initializing driver. For example, if you're google browser is 112 it would look like this :
driver = uc.Chrome(version_main=112, options=options )

2. It's auto installing a new version of undetected chromedriver the first time it runs. You may need to delete the old one before this works. Go to C:\Users\YOURUSERNAME\AppData\Roaming\undetected_chromedriver -> then delete undetected_chromedriver.exe

Please let me know if this helps.


@developers. The reason so many people are on older versions imo is because there are so many extensions issues on the most recent version of chrome with selenium and possibly uc. In my experience the newer versions do not play nice with extensions.
