### ISSUE TITLE
Changing user agent is detected !

### ISSUE THREAD

**Issue by PePinodemrs** [ultrafunkamsterdam/undetected-chromedriver#689]
Hi, i try to change my user agent but i'm being detected ;

Without changing the ua but just with the code i'm detected :

```driver.execute_cdp_cmd('Network.setUserAgentOverride', {"userAgent": driver.execute_script("return navigator.userAgent")})```

**Comment by PePinodemrs** [comment]
> It's easy to detect discripancies between your user agent and your actual browser or OS environment. So spoofing your user agent usually makes your script even more detectable as a bot.

yes but here i change the user agent by my default user agent so i do the manip like i change the user agent but in fact it not change

**Comment by sebdelsol** [comment]
Sure it won't work if you open a new window or tab, so you should use `"--user-agent"` command line switch.
Anyway spoofing your user user agent _is still a very bad idea_ since it's very easily detected : there are so many other ways to check your browser and environment... and any discrepancy will usually be flagged as very suspicious.

**Comment by PePinodemrs** [comment]
but my goal is not to change the user agent, just make it look like it is but put the same one back

**Comment by PePinodemrs** [comment]
by the way, do you know what constitutes a finger print? Apart from the user agent, the ip and the screen size?

**Comment by ultrafunkamsterdam** [comment]
changing user agent is not "detected"

User agent does nothing for detection.

test (windows):

this first step is important, since setting user agent only works for NEW chrome process (tree). so you have to make sure all chrome processes are killed

launch
cmd.exe
taskkill /f /im chrome*
"X:\Path\To\Google\Chrome\Application\chrome.exe" --user-agent="my user agent"
navigate to https://testnet.coinfaucet.eu/ or https://nowsecure.nl/
find out that it works fine
