### ISSUE TITLE
Support multiple dotted preferences

### ISSUE THREAD

**Issue by AlexGenKononov** [ultrafunkamsterdam/undetected-chromedriver#869]
Use case

```
chrome_options = uc.ChromeOptions()
profile = {
    "download.default_directory": "/home/ubuntu/Documents/",
    "download.prompt_for_download": False,
    "download.directory_upgrade": True,
    "download.extensions_to_open": "applications/pdf",
    "plugins.always_open_pdf_externally": True
}
chrome_options.add_experimental_option("prefs", profile)
```

Root cause - options.py
```
for key, value in prefs.items():
    undot_prefs.update(self._undot_key(key, value))
```
    
As a result just single key will be left within undot_prefs['download'] dict

Current Result:
```
undot_prefs = {
    'download': {'extensions_to_open': 'applications/pdf'},
    'plugins': {'always_open_pdf_externally': True}
}
```

Expected result:
```
undot_prefs = {
    'download': {
        'default_directory': '/home/ubuntu/Documents/',
        'prompt_for_download': False,
        'directory_upgrade': True,
        'extensions_to_open': 'applications/pdf'
    }
    'plugins': {
        'always_open_pdf_externally': True
    }     
}
```

**Comment by sebdelsol** [comment]
You're right, when I wrote that code I was not aware those prefs dict could be nested.

In my fork I actually fixed existing nested prefs found in the pref file... 
But forgot about the nested perfs given by the user.
Thanks a lot for that !

Anyway it's fixed in my [**fork**](https://github.com/sebdelsol/undetected-chromedriver).
[**Here's the change**](https://github.com/sebdelsol/undetected-chromedriver/commit/75c4a569516eafe291f11d1a1d0a117fae72353f).

I hope the author will be able to merge all this pull requests (#558)...
