### ISSUE TITLE
Not been able to add multiple extension

### ISSUE THREAD

**Issue by NimeMolla** [ultrafunkamsterdam/undetected-chromedriver#904]
Only the latest extension added into the driver. 
How to add multiple at the same time ??
Also tried to add as .crx but didn't successful. 
![code](https://user-images.githubusercontent.com/57084454/202454242-3a97c390-a78a-4138-ae81-a8be25794bc1.png)

**Comment by sebdelsol** [comment]
Sure if you want to load several extensions you've to provide a [**comma-separated list of path to those**](https://peter.sh/experiments/chromium-command-line-switches/#load-extension). 
Otherwise you'll end up with only the last one loaded.
```python3
extension_paths = (path1, path2, ...)
options.add_argument(f"--load-extension={','.join(extension_paths)}")
```

Zipped extensions (aka `.crx`) can't be loaded via command lines. There's `options.add_extension(crx_path)` available.
I haven't tried it tho. I'm not sure it would work since uc has already launched Chrome when the driver is instantiated...

**Comment by NimeMolla** [comment]
Sorry for this..😢
Thanks for the help ❤
